# =======================================================
# KITTY CONFIG - Terminess & Pink Palette
# =======================================================

# Tipografía
font_family      Terminess Nerd Font
bold_font        Terminess Nerd Font Bold
italic_font      Terminess Nerd Font Italic
bold_italic_font Terminess Nerd Font Bold Italic
font_size 12.0

# Cursor
cursor #ff2a85
cursor_text_color #000000
cursor_shape block
shell_integration disabled

# Scrollback
scrollback_lines 2000

# Relleno interno (Padding)
window_padding_width 8

# Bell
enable_audio_bell no

# =======================================================
# PALETA DE COLORES (Trollwut Pink Dark)
# =======================================================
foreground #ffffff
background #000000
selection_foreground #000000
selection_background #ff2a85

# Colores de bordes de pestañas
active_border_color #ff2a85
inactive_border_color #222222

# Black
color0 #000000
color8 #555555

# Red / Pink Accent
color1 #ff2a85
color9 #ff2a85

# Green
color2  #50fa7b
color10 #50fa7b

# Yellow
color3  #f1fa8c
color11 #f1fa8c

# Blue
color4  #bd93f9
color12 #bd93f9

# Magenta
color5  #ff2a85
color13 #ff2a85

# Cyan
color6  #8be9fd
color14 #8be9fd

# White
color7  #ffffff
color15 #ffffff
